api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import RestaurantViewSet

router = routers.DefaultRouter()
router.register(r'restaurants', RestaurantViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('restaurants/filter-by-opening-hours/', RestaurantViewSet.as_view({'get': 'action_filter_by_opening_hours'}), name='filter-by-opening-hours'),
    path('restaurants/<int:pk>/is_open/', RestaurantViewSet.as_view({'get': 'is_open'}), name='is_open'),
    path('restaurants/<int:pk>/average-rating/', RestaurantViewSet.as_view({'get': 'average_rating'}), name='restaurant-average-rating'),
    # path('restaurants/<int:pk>/latest-reviews/', RestaurantViewSet.as_view({'get': 'latest_reviews'}), name='restaurant-latest-reviews'),
    

]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls')),
    path('api/', include('api.urls')),
    path('food/', include('food.urls')),
    
]

restaurant/urls.py
from django.urls import path
from . import views

app_name = "restaurant"

urlpatterns = [
    # login + SignUp
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    
    # Base template
    path('base/', views.base, name='base'),
    path('base_location_restaurant/<int:pk>/',
         views.base_location_restaurant, name='base_location_restaurant'),
    path('search/', views.search_restaurants, name='search_restaurants'),


    # Restaurant CRUD
    path('', views.restaurant_list, name='restaurant_list'),
    path('restaurant_details/<int:pk>/', views.restaurant_details, name='restaurant_details'),
    path('restaurant_update/<int:pk>/',
         views.restaurant_update, name="restaurant_update"),
    path('restaurant_delete/<int:pk>/',
         views.restaurant_delete, name="restaurant_delete"),
    
    
    # Food CRUD
    path('food_list/', views.food_list, name='food_list'),
    path('food_update/<int:pk>/',
         views.food_update, name="food_update"),
    path('food_delete/<int:pk>/',
         views.food_delete, name="food_delete"),

]

restaurant/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError

class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Restaurant name'}),
            'description': forms.Textarea(),
            'rating': forms.NumberInput(attrs={'class': 'form-control'}),
            'location': forms.Select(attrs={'class': 'form-control'}),
            'cuisines': forms.CheckboxSelectMultiple(),
            'category': forms.CheckboxSelectMultiple(),
            'menus': forms.CheckboxSelectMultiple(),
        }
        
        
        
class OpeningHourForm(forms.ModelForm):
    WEEKDAY_CHOICES = [
        (1, 'Monday'),
        (2, 'Tuesday'),
        (3, 'Wednesday'),
        (4, 'Thursday'),
        (5, 'Friday'),
        (6, 'Saturday'),
        (7, 'Sunday'),
    ]
    weekday = forms.ChoiceField(choices=WEEKDAY_CHOICES)
    
    # validator to make sure that open_time is earlier than close_time
    def clean(self):
        cleaned_data = super().clean()
        open_time = cleaned_data.get('open_time')
        close_time = cleaned_data.get('close_time')

        if open_time and close_time and open_time >= close_time:
            raise ValidationError("Closing time must be later than opening time.")
        
        """ 
The clean method accesses the form's cleaned_data dictionary, which contains
the validated form field values.
We check if both the open_time and close_time fields are present and compare them.
If the close_time is earlier than or equal to the open_time, we raise a
ValidationError with a specified error message.
This validation ensures that the closing time cannot be set to a time earlier than the opening time.

"""
        

    class Meta:
        model=OpeningHour
        exclude=['restaurant']
        widgets={
            
            
            'open_time': forms.TimeInput(format='%H:%M', attrs={'type': 'time'}),
            'close_time': forms.TimeInput(format='%H:%M', attrs={'type': 'time'}),
            
            
        }
        
            
        

class FoodForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Restaurant name'}),
            'description': forms.Textarea(),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'ingredients': forms.CheckboxSelectMultiple(),
            'categories': forms.CheckboxSelectMultiple(),
            
        }
        
        

class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = '__all__'
        


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'

restaurant/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Restaurant, Location, Food, OpeningHour
from .forms import RestaurantForm, FoodForm, OpeningHourForm
from django.db.models import Q
# search with django-watson
from watson import search as watson
from watson import search as watson_search
from functools import reduce
import operator

# Pagination
from django.core.paginator import Paginator

# to test if the restaurant is actually open
from .helpers import is_restaurant_open



# location of restaurant for the base


def base(request):
    locations = Location.objects.all()
    return render(request, 'restaurant/base.html', {'locations': locations})


def base_location_restaurant(request, pk):
    # get the specific restaurant
    location = Location.objects.get(pk=pk)
    # get all the restaurants of the location
    restaurants = location.restaurants.all()

    context = {'location': location, 'restaurants': restaurants}
    return render(request, 'restaurant/location_restaurants.html', context)


# Login and SignUp

# login
def login(request):
    return render(request, 'restaurant/login.html')

# signup


def signup(request):
    return render(request, 'restaurant/signup.html')


def search_restaurants(request):
    location = request.GET.get('location')
    restaurant = request.GET.get('restaurant')

    q_objects = Q()

    if location:
        q_objects &= Q(location__name__icontains=location)

    if restaurant:
        search_fields = ['name', 'cuisines__name',
                         'menus__name', 'category__name']
        # q_objects &= Q(name__icontains=restaurant) | Q(cuisines__name__icontains=restaurant) | Q(category__name__icontains=restaurant)
        queries = [Q(**{field + '__icontains': restaurant})
                   for field in search_fields]
        # q_objects.append(reduce(operator.or_, queries))
        for query in queries:
            q_objects |= query

    restaurants = Restaurant.objects.filter(q_objects)
    search_query_str = str(q_objects)  # Convert Q object to string query

   # Use Watson's search function to perform the search
    search_results = watson_search.search(
        search_query_str, models=(Restaurant,))

    # restaurants = watson.filter(Restaurant, q_objects)
    # Perform the search query based on your requirements
    # restaurants = Restaurant.objects.filter(
    #     location__name__icontains=location,
    #     name__icontains=restaurant,
    #     # add more filters as needed
    # )
    
    
    # Pagination
    
    # set to 10 restaurants per pages
    paginator = Paginator(restaurants, 10)  
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'restaurants': restaurants,
        # print search_results and compare to restaurants
        'search_results': search_results,
        'location': location,
        'restaurant': restaurant,
        'page_obj':page_obj,
    }
    return render(request, 'restaurant/search_results.html', context)


"""  



def search_restaurants(request):
    location = request.GET.get('location')
    search_query = request.GET.get('search_query')
    cuisines = request.GET.getlist('cuisines')  # Assuming cuisines are selected as checkboxes
    menus = request.GET.getlist('menus')  # Assuming menus are selected as checkboxes

    q_objects = Q()

    if location:
        q_objects &= Q(location__name__icontains=location)

    if search_query:
        q_objects &= Q(name__icontains=search_query) | Q(cuisines__name__icontains=search_query) | Q(menus__name__icontains=search_query)

    if cuisines:
        q_objects &= Q(cuisines__name__in=cuisines)

    if menus:
        q_objects &= Q(menus__name__in=menus)

    restaurants = Restaurant.objects.filter(q_objects)

    context = {
        'restaurants': restaurants,
        'location': location,
        'search_query': search_query,
        'cuisines': cuisines,
        'menus': menus,
    }
    return render(request, 'search_results.html', context)
"""


def search_restaurants_watson(request):
    search_query = request.GET.get('search_query')

    if search_query:
        restaurants = watson.filter(Restaurant, search_query)
    else:
        restaurants = Restaurant.objects.all()

    context = {
        'restaurants': restaurants,
        'search_query': search_query,
    }
    return render(request, 'search_results.html', context)


# Restaurant CRUD


# list of restaurants
def restaurant_list(request):
    context = {}
    # get all the restaurants
    restaurants = Restaurant.objects.all()
    context['restaurants'] = restaurants
    # get the form
    form = RestaurantForm()
    context['form'] = form
    # create a new restaurant
    if request.method == 'POST':
        form = RestaurantForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('restaurant:restaurant_list')
        else:
            print(form.errors)

    return render(request, 'restaurant/restaurant_list.html', context)


# get the details of a restaurant
def restaurant_details(request, pk):
    restaurant = get_object_or_404(Restaurant, pk=pk)
    form = OpeningHourForm()
    if request.method == 'POST':
        form = OpeningHourForm(request.POST)
        if form.is_valid():
            # make sure that I do not have the same weekday set up many times

            # get the weekday of the form
            weekday = int(form.cleaned_data['weekday'])
            # get all the entry for that weekday for the specific restaurant
            existing_opening_hours = OpeningHour.objects.filter(
                restaurant=restaurant, weekday=weekday)
            # Check if existing opening hours exist for the specified weekday and restaurant combination
            if existing_opening_hours:
                # Delete existing opening hours
                existing_opening_hours.delete()

            # now save the form
            opening_hours = form.save(commit=False)
            opening_hours.restaurant = restaurant
            opening_hours.save()
            return redirect('restaurant:restaurant_details', pk=pk)
    else:
        print(form.errors)
        form = OpeningHourForm()

    # get the opening hours of the restaurant
    opening_hours = OpeningHour.objects.filter(restaurant=restaurant)
    context = {'restaurant': restaurant,
               'form': form, 'opening_hours': opening_hours}
    return render(request, 'restaurant/restaurant_details.html', context)

# update an existing restaurant


def restaurant_update(request, pk):
    restaurant = get_object_or_404(Restaurant, pk=pk)
    if request.method == 'POST':
        form = RestaurantForm(request.POST, instance=restaurant)
        if form.is_valid():
            form.save()
            return redirect('restaurant:restaurant_list')
    else:
        form = RestaurantForm(instance=restaurant)
    return render(request, 'restaurant/restaurant_list.html', {'form': form})


# delete an existing restaurant
def restaurant_delete(request, pk):
    restaurant = get_object_or_404(Restaurant, pk=pk)
    if request.method == 'POST':
        restaurant.delete()
        return redirect('restaurant_list')
    return render(request, 'restaurant/restaurant_delete.html', {'restaurant': restaurant})


# Food CRUD

def food_list(request):
    foods = Food.objects.all()
    form = FoodForm()
    context = {'foods': foods, 'form': form}
    if request.method == 'POST':
        form = FoodForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('restaurant:food_list')
    else:
        print(form.errors)

    return render(request, 'restaurant/food_list.html', context)


def food_update(request, pk):
    food = get_object_or_404(Food, pk=pk)
    if request.method == 'POST':
        form = FoodForm(request.POST, instance=food)
        if form.is_valid():
            form.save()
            return redirect('restaurant:food_list')
    else:
        form = FoodForm(instance=food)
    return render(request, 'restaurant/food_list.html', {'form': form})


def food_delete(request, pk):
    food = get_object_or_404(Food, pk=pk)
    if request.method == 'POST':
        food.delete()
        return redirect('food_list')
    return render(request, 'food_delete.html', {'food': food})

templates/restaurant/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Your App Name</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <h1>NDOCK</h1>
        </div>
        <div class="navbar-menu">
          <a class="navbar-item" href="{% url 'restaurant:restaurant_list' %}"
            >Add a Restaurant</a
          >
          <a class="navbar-item" href="{% url 'restaurant:login' %}">Log in</a>
          <a class="navbar-item" href="{% url 'restaurant:signup' %}"
            >Sign Up</a
          >
        </div>
      </div>
    </nav>

    {% block content %}
    <section class="hero is-medium">
      <div class="hero-image">
        <img
          src="{% static 'img/base/food_delivery_background.png' %}"
          alt="Hero Image"
        />
      </div>
      <div class="hero-body">
        <div class="container">
          <h1 class="title">Find the Best Restaurants Near You</h1>
          <div class="search-bar">
            <form action="{% url 'restaurant:search_restaurants' %}" method="GET">
              <input
                type="text"
                id="location"
                name="location"
                placeholder="Location"
              />
              <input
                type="text"
                id="restaurant"
                name="restaurant"
                placeholder="Search by name, cuisine, or category"
              />
              <button type="submit">Search</button>
            </form>
          </div>
        </div>
      </div>
    </section>

    {% endblock content %}

    <section class="restaurants-section">
      <div class="container">
        <ul>
          {% for location in locations %}
          <a href="{% url 'restaurant:base_location_restaurant' location.pk %}"
            ><li>{{location.name}}</li></a>

          {% endfor %}
        </ul>
      </div>
    </section>

    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col align-self-start">
            About NDOCK

            <ul>
              <li>Who We are</li>
              <li>Blog</li>
              <li>Work With Us</li>
              <li>Report Fraud</li>
            </ul>
          </div>
          <div class="col align-self-center">
            Learn More
            <ul>
              <li>Who We are</li>
              <li>Blog</li>
            </ul>
          </div>
          <div class="col align-self-end">
            Social Links

            <ul>
              <li>Who We are</li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

templates/restaurant/food_list.html
{% extends "restaurant/base.html" %}
{% load static %} 
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Food List</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="" />
  </head>
  <body>
    {% block content %}

    <h1>Foods List</h1>

    <ul>
      {% for food in foods %}
      <li>{{ food.name }} with the ingredients  {{ food.ingredients }}</li>
      {% endfor %}
    </ul>
    <br/>
    <h1>Create a Food</h1>
    <form method="post">
        {% csrf_token %}

        {{ form }}

        <button type="submit">Save</button>

    </form>


    {% endblock content %}

    <script src="" async defer></script>
  </body>
</html>

templates/restaurant/location_restaurants.html
{% extends 'restaurant/base.html' %} {% block content %}

<h1>Restaurants in {{ location.name }}</h1>
<ul>
  {% for restaurant in restaurants %}
  <li>{{ restaurant.name }} <a href="{% url 'restaurant:restaurant_update' restaurant.pk %}">Edit</a> </li> 
  {% endfor %}
</ul>
{% endblock content %}

templates/restaurant/restaurant_delete.html
{% extends "restaurant/base.html" %}

<form
  action="{% url 'restaurant:restaurant_delete' restaurant.pk %}"
  method="POST"
>
  {% csrf_token %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <i class="mdi mdi-check-all me-2"></i>
    <a href="{% url 'restaurant:restaurant_list' %}">Cancel? </a>
  </div>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <i class="mdi mdi-block-helper me-2"></i>
    <input type="submit" value="Delete!" />
  </div>
</form>

templates/restaurant/restaurant_details.html
{% extends "restaurant/base.html" %} {% block content %}

<h1>{{ restaurant.name }}</h1>
<h4>{{ restaurant.description }}</h4>
<h4>{{ restaurant.rating }}</h4>
<h4>{{ restaurant.location.name }}</h4>

{% if restaurant.is_open %}
    <p>Status: Open</p>
{% else %}
    <p>Status: Closed</p>
{% endif %}

<h1>{{ restaurant.name }} Opening Hours</h1>

{% for opening_hour in opening_hours %}
    <p>
        <strong>{{ opening_hour.get_weekday_display }}:</strong>
        {{ opening_hour.open_time|time:"H:i" }} -
        {{ opening_hour.close_time|time:"H:i" }}
    </p>
{% empty %}
    <p>No opening hours available.</p>
{% endfor %}


<h3>Set the Opening Hours</h3>
<form method="post" action="">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Save</button>

</form>

{% endblock content %}

templates/restaurant/restaurant_list.html
{% extends "restaurant/base.html" %}
{% load static %} 
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="" />
  </head>
  <body>
    {% block content %}

    <h1>Restaurants List</h1>

    <ul>
      {% for restaurant in restaurants %}
      <li> <a href="{% url 'restaurant:restaurant_details' restaurant.pk %}">{{ restaurant.name }}</a>   located at  {{ restaurant.location }}   <a href="{% url 'restaurant:restaurant_delete' restaurant.pk %}">Delete</a>  </li>
      {% endfor %}
    </ul>
    <br/>
    <h1>Create a Restaurant</h1>
    <form method="post">
        {% csrf_token %}

        {{ form }}

        <button type="submit">Save</button>

    </form>


    {% endblock content %}

    <script src="" async defer></script>
  </body>
</html>

templates/restaurant/search_results.html
{% extends "restaurant/base.html" %} {% block content %} {% if
page_obj.has_other_pages %}
<div class="pagination">
  {% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
  {% endif %}

  <span class="current-page">{{ page_obj.number }}</span>

  {% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}">Next</a>
  {% endif %}
</div>
{% if page_obj %}
<h2>Found Restaurants:</h2>
<ul>
  {% for restaurant in page_obj %}
  <li>
    <h3>{{ restaurant.name }}</h3>
    {% if restaurant.is_open %}
    <p>Status: Open</p>
    {% else %}
    <p>Status: Closed</p>
    {% endif %}
    <p>Location: {{ restaurant.location.name }}</p>
    <p>
      Cuisine: {% for cuisine in restaurant.cuisines.all %} {{ cuisine.name }}
      {% endfor %}
    </p>
    <p>
      <a href="{% url 'restaurant:restaurant_details' restaurant.pk %}"
        >View Details</a
      >
    </p>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No restaurants found.</p>
{% endif %} {% comment %} {% for restaurant in restaurants %}
<!-- Display the restaurant details here -->
<h2>{{ restaurant.name }}</h2>
<p>{{ restaurant.location }}</p>
<!-- Add more fields as needed -->
{% empty %}
<p>No restaurants found.</p>
{% endfor %} {% endcomment %} {% endblock content %}